name: Golang Build
on:
  workflow_call:
jobs:
  build:
    name: "${{ matrix.os }}, go-${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022]
        go: [1.17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Golang ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        working-directory: ./golang
        run: go build
      - name: Test
        working-directory: ./golang
        run: go test -v
