name: Golang Build
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'golang/**'
  push:
    branches:
      - master
    paths:
      - 'golang/**'
jobs:
  cpp_build:
    name: "Golang (${{ matrix.os }}, Go ${{ matrix.go }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        go: [1.17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Golang ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        working-directory: ./golang
        run: go build
